using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using LlamaLauncher.Models;

namespace LlamaLauncher.Services;

/// <summary>
/// Serialises the managed model profiles into the native llama.cpp INI preset
/// format (the <c>--models-preset</c> router file, see
/// https://github.com/ggml-org/llama.cpp/blob/master/docs/preset.md).
///
/// Each configured profile becomes a <c>[section]</c> whose name is the model id
/// used to address it in router mode. Keys are llama-server long options with the
/// leading dashes removed; booleans are written as <c>1</c>/<c>0</c> and Flash
/// Attention as <c>on</c>. The exact set of emitted keys mirrors
/// <see cref="LlamaServerLauncher.BuildArguments"/> so that launching a profile
/// through this app and launching llama-server directly against the INI produce
/// the same configuration.
///
/// Host/port are intentionally omitted from the per-model sections: in router
/// mode the server binds a single socket, so those belong on the llama-server
/// command line (they are surfaced in the file header comment instead).
/// </summary>
public sealed class PresetIniService
{
    private static readonly CultureInfo Ci = CultureInfo.InvariantCulture;

    /// <summary>Writes the preset to <paramref name="path"/> and returns the number of profiles written.</summary>
    public int Write(AppConfig config, string path)
    {
        var configured = config.Models.Values.Where(m => m.IsConfigured).ToList();

        var dir = Path.GetDirectoryName(Path.GetFullPath(path));
        if (!string.IsNullOrEmpty(dir))
            Directory.CreateDirectory(dir);

        File.WriteAllText(path, Build(config, path));
        return configured.Count;
    }

    /// <summary>Builds the full INI text. <paramref name="selfPath"/> is only used in the header comment.</summary>
    public string Build(AppConfig config, string? selfPath = null)
    {
        var configured = config.Models.Values.Where(m => m.IsConfigured).ToList();

        var host = string.IsNullOrWhiteSpace(configured.FirstOrDefault()?.Host)
            ? "127.0.0.1"
            : configured[0].Host;
        var port = (configured.FirstOrDefault()?.Port ?? 8080).ToString(Ci);
        var self = string.IsNullOrWhiteSpace(selfPath) ? "config.ini" : selfPath;

        var sb = new StringBuilder();
        sb.AppendLine("; llama-server model presets - generated by LlamaLauncher.");
        sb.AppendLine("; This is a llama.cpp INI preset (router mode). Editing it here is fine, but");
        sb.AppendLine("; the app overwrites it whenever profiles change.");
        sb.AppendLine("; Docs: https://github.com/ggml-org/llama.cpp/blob/master/docs/preset.md");
        sb.AppendLine(";");
        sb.AppendLine("; Launch the router directly from llama-server:");
        sb.AppendLine($";   llama-server --models-preset \"{self}\" --host {host} --port {port}");
        sb.AppendLine(";");
        sb.AppendLine("; Then address a model by its [section] name (the JSON \"model\" field), or set");
        sb.AppendLine("; load-on-startup = true under a section to have it load automatically.");
        sb.AppendLine();

        if (configured.Count == 0)
        {
            sb.AppendLine("; (no configured profiles yet)");
            return sb.ToString();
        }

        var used = new HashSet<string>(System.StringComparer.Ordinal);

        foreach (var m in configured)
        {
            var section = UniqueSection(SanitizeSection(m.ProfileName), used);

            sb.Append('[').Append(section).Append(']').AppendLine();
            Kv(sb, "model", Path.Combine(config.ModelsFolder, m.FileName));
            if (!string.IsNullOrWhiteSpace(m.Alias)) Kv(sb, "alias", m.Alias);

            Kv(sb, "n-gpu-layers", m.GpuLayers.ToString(Ci));
            if (m.NCpuMoe > 0) Kv(sb, "n-cpu-moe", m.NCpuMoe.ToString(Ci));
            if (m.FlashAttention) Kv(sb, "flash-attn", "on");
            Kv(sb, "ctx-size", m.ContextSize.ToString(Ci));

            if (m.SpeculativeEnabled && !string.IsNullOrWhiteSpace(m.SpecType))
            {
                Kv(sb, "spec-type", m.SpecType);
                Kv(sb, "spec-draft-n-max", m.SpecDraftNMax.ToString(Ci));
            }

            if (!string.IsNullOrWhiteSpace(m.CacheTypeK)) Kv(sb, "cache-type-k", m.CacheTypeK);
            if (!string.IsNullOrWhiteSpace(m.CacheTypeV)) Kv(sb, "cache-type-v", m.CacheTypeV);
            if (m.KvUnified) Kv(sb, "kv-unified", "1");

            // Integer perf flags: 0 means "omit - use llama-server's own default".
            if (m.Parallel > 0) Kv(sb, "parallel", m.Parallel.ToString(Ci));
            if (m.BatchSize > 0) Kv(sb, "batch-size", m.BatchSize.ToString(Ci));
            if (m.UBatchSize > 0) Kv(sb, "ubatch-size", m.UBatchSize.ToString(Ci));
            if (m.Threads > 0) Kv(sb, "threads", m.Threads.ToString(Ci));
            if (m.ThreadsBatch > 0) Kv(sb, "threads-batch", m.ThreadsBatch.ToString(Ci));
            if (m.ThreadsHttp > 0) Kv(sb, "threads-http", m.ThreadsHttp.ToString(Ci));

            // --no-mmap on the CLI == mmap disabled == mmap = 0 in the preset.
            if (m.NoMmap) Kv(sb, "mmap", "0");
            if (m.Mlock) Kv(sb, "mlock", "1");
            if (m.Jinja) Kv(sb, "jinja", "1");
            if (!string.IsNullOrWhiteSpace(m.ChatTemplateFile))
                Kv(sb, "chat-template-file", m.ChatTemplateFile.Trim());
            if (m.CacheReuse > 0) Kv(sb, "cache-reuse", m.CacheReuse.ToString(Ci));
            if (!string.IsNullOrWhiteSpace(m.ChatTemplateKwargs))
                Kv(sb, "chat-template-kwargs", m.ChatTemplateKwargs.Trim());
            if (m.Perf) Kv(sb, "perf", "1");

            if (m.SamplingEnabled)
            {
                Kv(sb, "temp", m.Temperature.ToString(Ci));
                Kv(sb, "top-p", m.TopP.ToString(Ci));
                Kv(sb, "top-k", m.TopK.ToString(Ci));
                Kv(sb, "min-p", m.MinP.ToString(Ci));
                Kv(sb, "presence-penalty", m.PresencePenalty.ToString(Ci));
            }

            if (!string.IsNullOrWhiteSpace(m.ExtraArgs))
            {
                // Keep the raw args as a comment for transparency, then translate the
                // long-form (--key value / --flag) ones into preset keys.
                sb.Append("; extra args: ").AppendLine(m.ExtraArgs.Trim());
                foreach (var (key, value) in ParseExtraArgs(m.ExtraArgs))
                    Kv(sb, key, value);
            }

            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static void Kv(StringBuilder sb, string key, string value)
        => sb.Append(key).Append(" = ").Append(value).AppendLine();

    /// <summary>Section headers are read verbatim between [ and ]; only strip brackets.</summary>
    private static string SanitizeSection(string name)
    {
        if (string.IsNullOrWhiteSpace(name)) return "model";
        var s = name.Replace('[', '(').Replace(']', ')').Trim();
        return s.Length == 0 ? "model" : s;
    }

    private static string UniqueSection(string basis, HashSet<string> used)
    {
        var candidate = basis;
        var i = 2;
        while (!used.Add(candidate))
            candidate = $"{basis} ({i++})";
        return candidate;
    }

    /// <summary>
    /// Translates a CLI-style extra-args string into preset key/value pairs.
    /// Only long options (<c>--name</c>) are converted; a following non-flag token
    /// becomes the value, otherwise the option is treated as a boolean (<c>= 1</c>).
    /// Short options are left to the verbatim comment written alongside.
    /// </summary>
    private static IEnumerable<(string Key, string Value)> ParseExtraArgs(string extra)
    {
        var tokens = Tokenize(extra);
        for (var i = 0; i < tokens.Count; i++)
        {
            var tok = tokens[i];
            if (!tok.StartsWith("--")) continue;

            var key = tok.TrimStart('-');
            if (key.Length == 0) continue;

            if (i + 1 < tokens.Count && !tokens[i + 1].StartsWith('-'))
            {
                yield return (key, tokens[i + 1]);
                i++;
            }
            else
            {
                yield return (key, "1");
            }
        }
    }

    private static List<string> Tokenize(string s)
    {
        var list = new List<string>();
        var sb = new StringBuilder();
        var inQuotes = false;

        foreach (var ch in s)
        {
            if (ch == '"')
            {
                inQuotes = !inQuotes;
            }
            else if (char.IsWhiteSpace(ch) && !inQuotes)
            {
                if (sb.Length > 0) { list.Add(sb.ToString()); sb.Clear(); }
            }
            else
            {
                sb.Append(ch);
            }
        }

        if (sb.Length > 0) list.Add(sb.ToString());
        return list;
    }
}
